feature(carticon):RR-0022:  Create cart icon
EimantasBlazevicius/PythonRemoteEE19 pull request #15
Opened 2023-12-23 01:42 UTC by Jann337

https://trello.com/c/TK0OIdJH/24-featrr-0022-create-cart-icon

2024-01-03 10:12 UTC, EimantasBlazevicius requested changes
In general products page is not complete yet, and if as a user I do not have products in cart and click on the cart I get an error page as well, as the query selecting the userdetail that does not exist does not work.

In general the program is broken in multiple places and it should not be in code review.

On additional note while I see that there is a lot of work done, if you fix it up I am willing to allow it, BUT in general you were tasked with creating the button in the navigation, that given the number would be able to show amount of products. and this is 43 files adjustment pull request. In any normal company you would be requested to delete it all together and do the task you have.

2024-01-03 10:12 UTC, EimantasBlazevicius commented on radicals/settings.py
> +    'crispy_bootstrap5',
add to requirements.txt

2024-01-03 10:12 UTC, EimantasBlazevicius commented on back_office/products/migrations/0001_initial.py
> +                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
with this validator you can not operate admin panel properly. keeps crashing.
Test your program before pushing it up for Code review

2024-01-06 10:18 UTC, EimantasBlazevicius approved these changes

2024-01-06 11:01 UTC, T6nisValk approved these changes

2024-01-06 11:05 UTC, merged