Feature(auth):RR-0025:Backoffice login flow
EimantasBlazevicius/PythonRemoteEE19 pull request #26
Opened 2024-01-07 10:46 UTC by KagouSurGit

2024-01-07 10:49 UTC, v1ljar approved these changes, later dismissed

2024-01-07 10:50 UTC, Jann337 submitted a review, later dismissed

2024-01-07 11:03 UTC, EimantasBlazevicius commented on back_office/supplier_login/views.py
> +		if form.is_valid():
Add a section to create UserDetails object associated with the user

2024-01-07 11:05 UTC, EimantasBlazevicius commented on back_office/supplier_login/views.py
> +		if form.is_valid():
Same how it was done in the front store auth that was fixed

2024-01-07 11:13 UTC, T6nisValk submitted a review, later dismissed

2024-01-11 19:10 UTC, EimantasBlazevicius requested changes
comment

2024-01-12 16:56 UTC, v1ljar approved these changes

2024-01-12 16:57 UTC, Jann337 approved these changes

2024-01-13 08:39 UTC, EimantasBlazevicius approved these changes

2024-01-14 08:25 UTC, merged