Feature(Authentication):RR-0018:Setup Login/Register flow
EimantasBlazevicius/PythonRemoteEE19 pull request #5
Opened 2023-12-10 12:11 UTC by KagouSurGit

https://trello.com/c/3InzUpcg/20-featrr-0018-setup-login-register-flow

2023-12-10 12:12 UTC, v1ljar approved these changes, later dismissed

2023-12-10 12:14 UTC, EimantasBlazevicius approved these changes, later dismissed

2023-12-10 12:14 UTC, EimantasBlazevicius commented on radicals/forms.py
> +from django import forms
All the authentication needs to be done in the "front_office/accounts_page" app

2023-12-14 13:29 UTC, T6nisValk commented
Navigation is created separately by me and included into the base, will finish it later today (14.12). I'm guessing you added it for testing purposes to the base file. - Shouldn't commit merge with current base.html changes?

I am not quite sure about this approach on authentication. Needs to have a separate app for it? I might have missed some class about dealing with forms.py?

2023-12-15 16:27 UTC, Jann337 approved these changes, later dismissed

2023-12-16 06:41 UTC, EimantasBlazevicius requested changes

2023-12-16 06:41 UTC, EimantasBlazevicius commented on radicals/forms.py
> +from django import forms
Move this file to the app where it will be used.

2023-12-16 06:41 UTC, EimantasBlazevicius commented on radicals/urls.py
> -"""radicals URL Configuration
radicals folder should have this urls.py file, your app should probably not even start without it.

2023-12-16 06:41 UTC, EimantasBlazevicius commented on templates/base.html
> +
remove empty line

2023-12-16 10:05 UTC, Jann337 approved these changes

2023-12-16 10:09 UTC, EimantasBlazevicius approved these changes

2023-12-16 10:14 UTC, merged